export declare const buttonGithubLink: string;
export declare const buttonSourceCode: string;
export declare const buttonSourceContainer: string;
export declare const cardContainer: string;
export declare const cardDescription: string;
export declare const cardImageContainer: string;
export declare const cardItem: string;
export declare const cardTextContainer: string;
export declare const cardTitleGroup: string;
